// Code generated by goctl. DO NOT EDIT.
package types

type AdminAdduserReq struct {
	Name     string `json:"name"`           //	姓名
	Phone    string `json:"phone,optional"` // 用户手机号
	Account  string `json:"account"`        // 账号
	Password string `json:"password"`       // 用户密码
	Email    string `json:"email"`          //邮箱
}

type AdminByPhonesGetUserReq struct {
	Phones string `json:"phones"` //	用户phone
}

type AdminByPhonesGetUserResp struct {
	Phones []string `json:"phones"` //	用户phone
}

type AdminByUidsGetUserReq struct {
	Uids string `json:"uids"` //用户uid，
}

type AdminByUidsGetUserResp struct {
	Uids []string `json:"uids"` //用户uid，
}

type AdminDeleteReq struct {
	Uid string `json:"uid"` // 用户唯一ID
}

type AdminDeleteUserReq struct {
	Uid string `json:"uid,optional"` // 删除用户id
}

type AdminDownImage struct {
	ImagePath string `form:"imagePath,optional"` //下载图片路径
}

type AdminForbidReq struct {
	Uid string `form:"uid"`
}

type AdminForbiddenReq struct {
	Uid        string `json:"uid,optional"`        // 用户唯一ID
	ActionType int64  `json:"actionType,optional"` //是否禁用，0正常，1禁用
}

type AdminGetByAccountReq struct {
	Account string `form:"account,optional"` // 姓名，账号，或者手机号
}

type AdminGetByAccountRes struct {
	Uid        string `gorm:"primaryKey" json:"uid,optional"` // 用户唯一ID
	Phone      string `json:"phone,optional"`                 // 用户手机号
	Account    string `json:"account,optional"`               // 账户
	CreateTime int64  `json:"createTime,optional"`            //注册时间
	IsDisable  int64  `json:"isDisable,optional"`             //是否禁用，0正常，1禁用
	UpdateTime int64  `json:"updateTime,optional"`            //更新时间
	Email      string `json:"email,optional"`                 //邮箱
}

type AdminGetUserInfoReq struct {
	Uid string `form:"uid,optional"` // 用户唯一ID
}

type AdminGetUserInfoResp struct {
	Uid           string `gorm:"primaryKey" json:"uid,optional"`            // 用户唯一ID
	Phone         string `json:"phone,optional"`                            // 用户手机号
	Name          string `json:"name,optional"`                             // 昵称
	Account       string `json:"account,optional"`                          // 账号/手机号/邮箱/
	Avatar        string `json:"avatar,optional"   gorm:"column:newAvatar"` // 头像路径
	LoginTimes    int64  `json:"loginTimes,optional"`                       //登录次数
	LastLoginTime int64  `json:"lastLoginTime,optional"`                    //最后登录时间
	CreateTime    int64  `json:"createTime,optional"`                       //注册时间
	UpdateTime    int64  `json:"updateTime,optional"`                       //更新时间
	Email         string `json:"email,optional"`                            //邮箱
}

type AdminInfoResp struct {
	Name       string `json:"name,optional"`                  //姓名
	Uid        string `gorm:"primaryKey" json:"uid,optional"` // 用户唯一ID
	Phone      string `json:"phone,optional"`                 // 用户手机号
	Account    string `json:"account,optional"`               // 账户
	Avatar     string `json:"avatar,optional"`                // 头像路径
	CreateTime int64  `json:"createTime,optional"`            //注册时间
	UpdateTime int64  `json:"updateTime,optional"`            //更新时间
	Email      string `json:"email,optional"`                 //邮箱
}

type AdminItem struct {
	Uid        string `gorm:"primaryKey" json:"uid,optional"` // 用户唯一ID
	Avatar     string `json:"avatar,optional"`                // 头像路径
	Phone      string `json:"phone,optional"`                 // 用户手机号
	Account    string `json:"account,optional"`               // 账户
	CreateTime int64  `json:"createTime,optional"`            // 注册时间
	IsDisable  int64  `json:"isDisable,optional"`             // 是否禁用，0正常，1禁用
	UpdateTime int64  `json:"updateTime,optional"`            // 更新时间
	Email      string `json:"email,optional"`                 // 邮箱
	Name       string `json:"name,optional"`                  // 姓名
	Otp        int64  `json:"otp"`                            // 二次验证状态 1开启 2关闭
}

type AdminListReq struct {
	Page    int64  `form:"page,optional"`    // 当前页
	Size    int64  `form:"size,optional"`    // 查询大小
	Account string `form:"account,optional"` // 待查看的用户账号
	Name    string `form:"name,optional"`    // 用户姓名
	Phone   string `form:"phone,optional"`   // 用户手机号
}

type AdminListRes struct {
	Total int64        `json:"total,optional"` // 总数
	List  []*AdminItem `json:"list,optional"`  // 列表
}

type AdminLoadImages struct {
	Images []string `form:"images,optional"` //上传图片切片
}

type AdminResetPasswordReq struct {
	Uid           string `gorm:"primaryKey" json:"uid"` // 被更新用户的id
	NewPassword   string `json:"newPassword"`           //新密码
	ReNewPassword string `json:"reNewPassword"`         //确认密码
}

type AdminUpdateReq struct {
	Uid      string `json:"uid"`               // admin用户uid
	Phone    string `json:"phone,optional"`    // 用户手机号
	Email    string `json:"email,optional"`    // 邮箱
	Password string `json:"password,optional"` // password 可选
	Name     string `json:"name,optional"`     //	姓名
}

type AdminUserInfoReq struct {
	Id uint64 `json:"id,optional"` // 用户ID
}

type AdminUserInfoRes struct {
	Account string `json:"account,optional"`  // 账号
	Name    string `json:"nickname,optional"` // 用户姓名
	Mobile  string `json:"mobile,optional"`   // 手机号
}

type AdminUserListItme struct {
	Uid        string `json:"uid,optional"`        // 用户唯一ID
	Name       string `json:"name"`                // 名称
	Account    string `json:"account"`             // 账号/手机号/邮箱/
	CreateTime int64  `json:"createTime,optional"` //注册时间
	IsDisable  int64  `json:"isDisable,optional"`  //是否禁用，0正常，1禁用
	UpdateTime int64  `json:"updateTime,optional"` //更新时间
}

type AdminUserListReq struct {
	Page      int64  `form:"page,optional"`      // 当前页
	Size      int64  `form:"size,optional"`      // 查询大小
	Account   string `form:"account,optional"`   // 待查看的用户账号
	IsDisable int64  `form:"isDisable,optional"` // 是否禁用，0正常，1禁用
	StartTime int64  `form:"startTime,optional"` // 注册时间范围，开始时间
	EndTime   int64  `form:"endTime,optional"`   // 注册时间范围，结束时间
}

type AdminUserListRes struct {
	Total int64                `json:"total,optional"` // 总数
	List  []*AdminUserListItme `json:"list,optional"`  // 列表
}

type CertAddReq struct {
	Name     string `json:"name"` // 凭证名称 唯一
	Desc     string `json:"desc"` // 凭证备注
	Type     uint64 `json:"type"` // 类型
	Account  string `json:"account"`
	Password string `json:"password"`
	Secret   string `json:"secret"`
}

type CertDeleteReq struct {
	Id uint64 `json:"id,optional"` //凭证ID
}

type CertItem struct {
	Id      uint64 `json:"id,optional"`   //凭证ID
	Name    string `json:"name,optional"` //凭证名称
	Desc    string `json:"desc"`          // 凭证备注
	Type    uint64 `json:"type"`          // 凭证类型 1/2 账号密码/密钥
	Account string `json:"account"`       // 账号
	HostNum uint64 `json:"hostNum"`
}

type CertListReq struct {
	Page int64  `form:"page,optional"` // 当前页
	Size int64  `form:"size,optional"` // 查询大小
	Name string `form:"name,optional"` // 凭证名称
}

type CertListResp struct {
	Total int64       `json:"total,optional"` // 总数
	List  []*CertItem `json:"list,optional"`  // 列表
}

type CertOption struct {
	Id   uint64 `json:"id,optional"`     //凭证ID
	Name string `json:"string,optional"` //凭证名称
}

type CertOptionResp struct {
	Item []*CertOption `json:"item"`
}

type CertUpdateReq struct {
	Id       uint64 `json:"id,optional"` //凭证ID
	Name     string `json:"name"`        // 凭证名称 唯一
	Desc     string `json:"desc"`        // 凭证备注
	Type     uint64 `json:"type"`        // 类型
	Account  string `json:"account"`
	Password string `json:"password"`
	Secret   string `json:"secret"`
}

type CloseOTPReq struct {
	UID string `json:"uid"`
}

type HostAddReq struct {
	Name        string   `json:"name"` // 主机名称
	Desc        string   `json:"desc"` // 备注
	Tags        []uint64 `json:"tags"` // 对应标签
	Address     string   `json:"address"`
	AutoInstall bool     `json:"autoInstall"` // 自动安装
	IP          string   `json:"ip"`          // 主机IP
	Port        int      `json:"port"`        // SSH端口
	CertId      uint64   `json:"certId"`      // 凭证ID
	Type        uint64   `json:"type"`
	Account     string   `json:"account"`  // SSH 账号
	Password    string   `json:"password"` // SSH 密码
	Secret      string   `json:"secret"`   // SSH 私钥
	AutoCert    bool     `json:"autoCert"` // 自动同步创建凭证
	NotSave     bool     `json:"notSave"`  // 不保存SSH登陆凭证信息
}

type HostAddResp struct {
	ConsoleRPCAddr string `json:"consoleRpcAddr"`
	UUid           string `json:"uuid"`
	Secret         string `json:"secret"`
}

type HostDeleteReq struct {
	Id uint64 `json:"id"`
}

type HostItem struct {
	Id           uint64 `json:"id,optional"`   //ID
	Name         string `json:"name,optional"` //名称
	Desc         string `json:"desc"`          // 备注
	Address      string `json:"ip"`
	State        uint64 `json:"state"`
	CPU          string `json:"cpu"`
	Mem          string `json:"mem"`
	LastUploadAt int64  `json:"lastUploadAt"`
}

type HostListReq struct {
	Page    int64  `form:"page,optional"` // 当前页
	Size    int64  `form:"size,optional"` // 查询大小
	Name    string `form:"name,optional"` // 名称
	Address string `json:"address"`       // ip
}

type HostListResp struct {
	Total int64       `json:"total,optional"` // 总数
	List  []*HostItem `json:"list,optional"`  // 列表
}

type HostUpdateReq struct {
	Id      uint64   `json:"id"`
	Name    string   `json:"name"`    // 主机名称
	Desc    string   `json:"desc"`    // 备注
	Tags    []uint64 `json:"tags"`    // 对应标签
	Address string   `json:"address"` //
}

type LoginReq struct {
	Username string `json:"username"`         // 账号
	Password string `json:"password"`         // 密码
	OTPCode  string `json:"otpCode,optional"` // 二次验证码
}

type LoginResp struct {
	ID            uint64 `json:"id"`
	Name          string `json:"nickname"`
	Username      string `json:"username"`
	Avatar        string `json:"avatar"`
	LastLoginTime string `json:"last_login_time"`
	Token         string `json:"token"` // 登录令牌
}

type OTPStateReq struct {
	Account string `form:"account"`
}

type OTPStateResp struct {
	Enable bool `json:"enable"`
}

type OpenOTPInfo struct {
	Data string `json:"data"`
}

type RuleAddReq struct {
	GroupId   uint64   `json:"groupId"`
	Tags      []uint64 `json:"tags"`
	Interface string   `json:"interface"` // 网卡
	SIP       string   `json:"sip"`
	SPort     string   `json:"sport"`
	DIP       string   `json:"dip"`
	DPort     string   `json:"dport"`
	Option    string   `json:"option"` // 操作 accept/drop
	Enable    bool     `json:"enable"` // 启用
	Desc      string   `json:"desc"`   // 描述
	Name      string   `json:"name"`   // 名称
}

type RuleDeleteReq struct {
	Id uint64 `json:"id"`
}

type RuleGroupAddReq struct {
	Name string   `json:"name"` // 分组名称 唯一
	Desc string   `json:"desc"` // 分组备注
	Tags []uint64 `json:"tags"`
}

type RuleGroupDeleteReq struct {
	Id uint64 `json:"id,optional"` //规则分组ID
}

type RuleGroupItem struct {
	Id      uint64   `json:"id,optional"`   //规则分组ID
	Name    string   `json:"name,optional"` //规则分组名称
	Desc    string   `json:"desc"`          // 规则分组备注
	RuleNum uint64   `json:"ruleNum"`       // 关联的规则数
	Tags    []uint64 `json:"tags"`
}

type RuleGroupListReq struct {
	Page int64  `form:"page,optional"` // 当前页
	Size int64  `form:"size,optional"` // 查询大小
	Name string `form:"name,optional"` // 规则分组名称
}

type RuleGroupListResp struct {
	Total int64            `json:"total,optional"` // 总数
	List  []*RuleGroupItem `json:"list,optional"`  // 列表
}

type RuleGroupOption struct {
	Id   uint64 `json:"id,optional"`     //规则分组ID
	Name string `json:"string,optional"` //规则分组名称
}

type RuleGroupOptionResp struct {
	Item []*RuleGroupOption `json:"item"`
}

type RuleGroupUpdateReq struct {
	Id   uint64   `json:"id,optional"` //规则分组ID
	Name string   `json:"name"`        // 规则分组名称 唯一
	Desc string   `json:"desc"`        // 规则分组备注
	Tags []uint64 `json:"tags"`
}

type RuleItem struct {
	Id        uint64   `json:"id,optional"`   //规则ID
	Name      string   `json:"name,optional"` //规则名称
	GroupId   uint64   `json:"groupId"`
	GroupName string   `json:"groupName,optional"` //规则名称
	Enable    bool     `json:"enable"`             // 启用
	Interface string   `json:"interface"`          // 网卡
	SIP       string   `json:"sip"`
	SPort     string   `json:"sport"`
	DIP       string   `json:"dip"`
	DPort     string   `json:"dport"`
	Option    string   `json:"option"` // 操作 accept/drop
	Tags      []uint64 `json:"tags"`
}

type RuleListReq struct {
	Page    int64  `form:"page,optional"` // 当前页
	Size    int64  `form:"size,optional"` // 查询大小
	Name    string `form:"name,optional"` // 规则名称
	GroupId uint64 `form:"groupId,optional"`
}

type RuleListResp struct {
	Total int64       `json:"total,optional"` // 总数
	List  []*RuleItem `json:"list,optional"`  // 列表
}

type RuleUpdateReq struct {
	Id        uint64   `json:"id"`
	GroupId   uint64   `json:"groupId"`
	Tags      []uint64 `json:"tags"`
	Interface string   `json:"interface"` // 网卡
	SIP       string   `json:"sip"`
	SPort     string   `json:"sport"`
	DIP       string   `json:"dip"`
	DPort     string   `json:"dport"`
	Option    string   `json:"option"` // 操作 accept/drop
	Enable    bool     `json:"enable"` // 启用
	Desc      string   `json:"desc"`   // 描述
	Name      string   `json:"name"`   // 名称
}

type SaveOTPReq struct {
	Code string `json:"code"`
}

type TagAddReq struct {
	Name string `json:"name"` // 标签名称 唯一
	Desc string `json:"desc"` // 标签备注
}

type TagDeleteReq struct {
	Id uint64 `json:"email,optional"` //标签ID
}

type TagItem struct {
	Id           uint64 `json:"email,optional"`  //标签ID
	Name         string `json:"string,optional"` //标签名称
	Desc         string `json:"desc"`            // 标签备注
	HostNum      uint64 `json:"hostNum"`         // 关联的主机数
	RuleNum      uint64 `json:"ruleNum"`         // 关联的规则数
	RuleGroupNum uint64 `json:"ruleGroupNum"`    // 关联的规则集数
}

type TagListReq struct {
	Page int64  `form:"page,optional"` // 当前页
	Size int64  `form:"size,optional"` // 查询大小
	Name string `form:"name,optional"` // 标签名称
}

type TagListResp struct {
	Total int64      `json:"total,optional"` // 总数
	List  []*TagItem `json:"list,optional"`  // 列表
}

type TagOption struct {
	Id   uint64 `json:"id,optional"`     //标签ID
	Name string `json:"string,optional"` //标签名称
}

type TagOptionResp struct {
	Item []*TagOption `json:"item"`
}

type TagUpdateReq struct {
	Id   uint64 `json:"id"`   // 标签ID
	Name string `json:"name"` // 标签名称 唯一
	Desc string `json:"desc"` // 标签备注
}
