// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminAvatarsFieldNames          = builder.RawFieldNames(&AdminAvatars{})
	adminAvatarsRows                = strings.Join(adminAvatarsFieldNames, ",")
	adminAvatarsRowsExpectAutoSet   = strings.Join(stringx.Remove(adminAvatarsFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminAvatarsRowsWithPlaceHolder = strings.Join(stringx.Remove(adminAvatarsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cache4HfireAdminAvatarsIdPrefix = "cache:4Hfire:adminAvatars:id:"
)

type (
	adminAvatarsModel interface {
		Insert(ctx context.Context, data *AdminAvatars) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminAvatars, error)
		Update(ctx context.Context, data *AdminAvatars) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminAvatarsModel struct {
		sqlc.CachedConn
		table string
	}

	AdminAvatars struct {
		Id     int64          `db:"id"`     // 用户id
		Avatar sql.NullString `db:"avatar"` // 用户头像
	}
)

func newAdminAvatarsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminAvatarsModel {
	return &defaultAdminAvatarsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`adminAvatars`",
	}
}

func (m *defaultAdminAvatarsModel) Delete(ctx context.Context, id int64) error {
	_4HfireAdminAvatarsIdKey := fmt.Sprintf("%s%v", cache4HfireAdminAvatarsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, _4HfireAdminAvatarsIdKey)
	return err
}

func (m *defaultAdminAvatarsModel) FindOne(ctx context.Context, id int64) (*AdminAvatars, error) {
	_4HfireAdminAvatarsIdKey := fmt.Sprintf("%s%v", cache4HfireAdminAvatarsIdPrefix, id)
	var resp AdminAvatars
	err := m.QueryRowCtx(ctx, &resp, _4HfireAdminAvatarsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminAvatarsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminAvatarsModel) Insert(ctx context.Context, data *AdminAvatars) (sql.Result, error) {
	_4HfireAdminAvatarsIdKey := fmt.Sprintf("%s%v", cache4HfireAdminAvatarsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, adminAvatarsRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Id, data.Avatar)
	}, _4HfireAdminAvatarsIdKey)
	return ret, err
}

func (m *defaultAdminAvatarsModel) Update(ctx context.Context, data *AdminAvatars) error {
	_4HfireAdminAvatarsIdKey := fmt.Sprintf("%s%v", cache4HfireAdminAvatarsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminAvatarsRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Avatar, data.Id)
	}, _4HfireAdminAvatarsIdKey)
	return err
}

func (m *defaultAdminAvatarsModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cache4HfireAdminAvatarsIdPrefix, primary)
}

func (m *defaultAdminAvatarsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminAvatarsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminAvatarsModel) tableName() string {
	return m.table
}
